<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>New Request (1)</name>
   <tag></tag>
   <elementGuidId>bd3a8bbb-7359-47e4-9c2e-ed1b53b3fb4e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <katalonVersion>8.5.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>${URL_API_INTERNE}/v1/fournisseurs/fournisseursactifetvalide?pageNo=1&amp;orderBy=ID&amp;orderDirection=ASC</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.URL_API_INTERNE</defaultValue>
      <description></description>
      <id>b57229fa-9b42-4d0a-b79b-b40302e3bc5c</id>
      <masked>false</masked>
      <name>URL_API_INTERNE</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
