<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>GET FOURNISSEUR</name>
   <tag></tag>
   <elementGuidId>71925d08-68c9-42c2-b1c6-c96c20966778</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <katalonVersion>8.5.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>${URL_API_INTERNE}/v1/fournisseurs/06221fc0-517e-416d-bb4f-67644eff10c9</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.URL_API_INTERNE</defaultValue>
      <description></description>
      <id>ac769571-532d-4e88-8160-12755dab8a92</id>
      <masked>false</masked>
      <name>URL_API_INTERNE</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
